name: ${project.name}
description: ${project.description}
version: ${project.version}

author: arboriginal
website: https://www.spigotmc.org/resources/${spigot-id}/
dev-url: https://github.com/arboriginal/${project.artifactId}

main: ${project.groupId}.${project.artifactId}.${spigot-main}
api-version: ${spigot-api}

commands:
  sb-reload:
    description: Reload the plugin configuration
    permission: scaffold

permissions:
  sb.reload:
    description: Allows to use the /scaffold command
    default: op

  sb.vanilla_scaffoldings.bridge:
    description: Allows to create long bridges with vanilla scaffoldings
    default: true

  # /!\ REMEMBER: The next permissions are required for their described action (of course...)
  # But the players also have to old a specific item in off hand to use them (see « offHandTools » in config.yml).
  # This prevent players to be forced to always use those behaviors when they tried to do something else ...
  # ... like ... build! (oh wait really? players build in Minecraft??? :p)

  sb.alt_scaffolding.break: # /!\ Doesn't prevent to break normally!
    description: Allows to break alternative blocks like scaffolding (chain reaction)
    default: false

  sb.alt_scaffolding.place:
    description: Allows to place alternative blocks like scaffolding (from bottom to up / from top to side)
    default: true
